#!/bin/sh
[ -e "$HOME/.cache/wal/colors.sh" ] && . "${HOME}/.cache/wal/colors.sh"

actions=("lock\nrestart\nshutdown\nsuspend\nhibernate")
action=$(echo -e $actions | dmenu -l 5 -c -i -fn "monospace:size=13" -m "0" -p ">>" -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15")
case "$action" in
    lock)
        betterlockscreen -l
        ;;

    restart)
        sudo systemctl reboot
        ;;

    shutdown)
        sudo systemctl poweroff
        ;;

    suspend)
        sudo systemctl suspend
        ;;

    hibernate)
        sudo systemctl hibernate
        ;;
esac
